/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        dark: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        purple: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c3aed',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
        success: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        background: {
          light: '#ffffff',
          'light-secondary': '#f8f9fa',
          'light-tertiary': '#e9ecef',
          dark: '#0a0a0a',
          'dark-secondary': '#1a1a1a',
          'dark-tertiary': '#2a2a2a',
        },
        text: {
          'light-primary': '#1a1a1a',
          'light-secondary': '#495057',
          'light-tertiary': '#6c757d',
          'dark-primary': '#ffffff',
          'dark-secondary': '#e5e5e5',
          'dark-tertiary': '#a3a3a3',
        },
        border: {
          light: '#e5e7eb',
          dark: '#374151',
          gradient: 'linear-gradient(135deg, #8b5cf6, #3b82f6)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        DEFAULT: '0.375rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0 2px 15px 0 rgba(0, 0, 0, 0.1)',
        'medium': '0 4px 20px 0 rgba(0, 0, 0, 0.15)',
        'hard': '0 10px 40px 0 rgba(0, 0, 0, 0.2)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'dark-soft': '0 2px 15px 0 rgba(0, 0, 0, 0.3)',
        'dark-medium': '0 4px 20px 0 rgba(0, 0, 0, 0.4)',
        'dark-hard': '0 10px 40px 0 rgba(0, 0, 0, 0.5)',
        'glow-blue': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-purple': '0 0 20px rgba(139, 92, 246, 0.3)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'slide-left': 'slideLeft 0.5s ease-out',
        'slide-right': 'slideRight 0.5s ease-out',
        'bounce-gentle': 'bounceGentle 2s infinite',
        'pulse-soft': 'pulseSoft 2s infinite',
        'gradient-border': 'gradientBorder 3s ease-in-out infinite',
        'chart-reveal': 'chartReveal 1s ease-out',
        'theme-transition': 'themeTransition 0.3s ease-in-out',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        gradientBorder: {
          '0%, 100%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
        },
        chartReveal: {
          '0%': { transform: 'scaleY(0)', transformOrigin: 'bottom' },
          '100%': { transform: 'scaleY(1)', transformOrigin: 'bottom' },
        },
        themeTransition: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(59, 130, 246, 0.2)' },
          '100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.6)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-primary': 'linear-gradient(135deg, #3b82f6, #1d4ed8)',
        'gradient-purple': 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
        'gradient-blue-purple': 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
        'gradient-dark': 'linear-gradient(135deg, #0f172a, #1e293b)',
        'gradient-border': 'linear-gradient(135deg, #8b5cf6, #3b82f6, #8b5cf6)',
        'hero-gradient': 'linear-gradient(135deg, #1e40af 0%, #3b82f6 50%, #8b5cf6 100%)',
        'card-gradient': 'linear-gradient(145deg, rgba(255,255,255,0.1), rgba(255,255,255,0.05))',
        'card-gradient-dark': 'linear-gradient(145deg, rgba(0,0,0,0.1), rgba(0,0,0,0.05))',
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
        '3xl': '32px',
      },
      zIndex: {
        '1': '1',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [
    function({ addUtilities, theme }) {
      const newUtilities = {
        '.gradient-border': {
          position: 'relative',
          background: 'linear-gradient(135deg, #8b5cf6, #3b82f6)',
          'border-radius': theme('borderRadius.lg'),
          padding: '2px',
        },
        '.gradient-border::before': {
          content: '""',
          position: 'absolute',
          top: '2px',
          left: '2px',
          right: '2px',
          bottom: '2px',
          background: theme('colors.white'),
          'border-radius': 'calc(' + theme('borderRadius.lg') + ' - 2px)',
          'z-index': '-1',
        },
        '.gradient-border-dark::before': {
          background: theme('colors.background.dark'),
        },
        '.glass': {
          background: 'rgba(255, 255, 255, 0.1)',
          'backdrop-filter': 'blur(10px)',
          border: '1px solid rgba(255, 255, 255, 0.2)',
        },
        '.glass-dark': {
          background: 'rgba(0, 0, 0, 0.1)',
          'backdrop-filter': 'blur(10px)',
          border: '1px solid rgba(255, 255, 255, 0.1)',
        },
        '.container-custom': {
          width: '100%',
          'margin-left': 'auto',
          'margin-right': 'auto',
          'padding-left': theme('spacing.4'),
          'padding-right': theme('spacing.4'),
          '@media (min-width: 640px)': {
            'max-width': '640px',
            'padding-left': theme('spacing.6'),
            'padding-right': theme('spacing.6'),
          },
          '@media (min-width: 768px)': {
            'max-width': '768px',
            'padding-left': theme('spacing.8'),
            'padding-right': theme('spacing.8'),
          },
          '@media (min-width: 1024px)': {
            'max-width': '1024px',
          },
          '@media (min-width: 1280px)': {
            'max-width': '1280px',
          },
          '@media (min-width: 1536px)': {
            'max-width': '1536px',
          },
        },
        '.text-gradient': {
          background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
          '-webkit-background-clip': 'text',
          '-webkit-text-fill-color': 'transparent',
          'background-clip': 'text',
        },
        '.btn-primary': {
          background: 'linear-gradient(135deg, #3b82f6, #1d4ed8)',
          color: theme('colors.white'),
          padding: theme('spacing.3') + ' ' + theme('spacing.6'),
          'border-radius': theme('borderRadius.lg'),
          'font-weight': theme('fontWeight.semibold'),
          transition: 'all 0.3s ease',
          border: 'none',
          cursor: 'pointer',
        },
        '.btn-primary:hover': {
          background: 'linear-gradient(135deg, #1d4ed8, #1e40af)',
          transform: 'translateY(-2px)',
          'box-shadow': theme('boxShadow.glow-blue'),
        },
        '.btn-secondary': {
          background: 'transparent',
          color: theme('colors.primary.600'),
          padding: theme('spacing.3') + ' ' + theme('spacing.6'),
          'border-radius': theme('borderRadius.lg'),
          'font-weight': theme('fontWeight.semibold'),
          border: '2px solid ' + theme('colors.primary.600'),
          transition: 'all 0.3s ease',
          cursor: 'pointer',
        },
        '.btn-secondary:hover': {
          background: theme('colors.primary.600'),
          color: theme('colors.white'),
          transform: 'translateY(-2px)',
          'box-shadow': theme('boxShadow.glow-blue'),
        },
        '.btn-ghost': {
          background: 'transparent',
          color: theme('colors.text.light-primary'),
          padding: theme('spacing.2') + ' ' + theme('spacing.4'),
          'border-radius': theme('borderRadius.md'),
          'font-weight': theme('fontWeight.medium'),
          border: 'none',
          transition: 'all 0.3s ease',
          cursor: 'pointer',
        },
        '.btn-ghost:hover': {
          background: theme('colors.background.light-secondary'),
          color: theme('colors.primary.600'),
        },
        '.dark .btn-ghost': {
          color: theme('colors.text.dark-primary'),
        },
        '.dark .btn-ghost:hover': {
          background: theme('colors.background.dark-secondary'),
          color: theme('colors.primary.400'),
        },
        '.input-field': {
          width: '100%',
          padding: theme('spacing.3') + ' ' + theme('spacing.4'),
          'border-radius': theme('borderRadius.lg'),
          border: '2px solid ' + theme('colors.border.light'),
          background: theme('colors.background.light'),
          color: theme('colors.text.light-primary'),
          transition: 'all 0.3s ease',
          'font-size': theme('fontSize.base')[0],
          'line-height': theme('fontSize.base')[1].lineHeight,
        },
        '.input-field:focus': {
          outline: 'none',
          'border-color': theme('colors.primary.500'),
          'box-shadow': '0 0 0 3px rgba(59, 130, 246, 0.1)',
        },
        '.dark .input-field': {
          'border-color': theme('colors.border.dark'),
          background: theme('colors.background.dark-secondary'),
          color: theme('colors.text.dark-primary'),
        },
        '.dark .input-field:focus': {
          'border-color': theme('colors.primary.400'),
          'box-shadow': '0 0 0 3px rgba(59, 130, 246, 0.2)',
        },
        '.card-interactive': {
          background: theme('colors.background.light'),
          border: '1px solid ' + theme('colors.border.light'),
          'border-radius': theme('borderRadius.xl'),
          padding: theme('spacing.6'),
          transition: 'all 0.3s ease',
          cursor: 'pointer',
          'box-shadow': theme('boxShadow.soft'),
        },
        '.card-interactive:hover': {
          transform: 'translateY(-4px)',
          'box-shadow': theme('boxShadow.medium'),
          'border-color': theme('colors.primary.300'),
        },
        '.dark .card-interactive': {
          background: theme('colors.background.dark-secondary'),
          'border-color': theme('colors.border.dark'),
          'box-shadow': theme('boxShadow.dark-soft'),
        },
        '.dark .card-interactive:hover': {
          'box-shadow': theme('boxShadow.dark-medium'),
          'border-color': theme('colors.primary.600'),
        },
        '.loading-skeleton': {
          background: 'linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%)',
          'background-size': '200% 100%',
          animation: 'shimmer 2s infinite',
        },
        '.dark .loading-skeleton': {
          background: 'linear-gradient(90deg, #2a2a2a 25%, #3a3a3a 50%, #2a2a2a 75%)',
          'background-size': '200% 100%',
        },
        '.focus-ring': {
          'outline-offset': '2px',
          outline: '2px solid transparent',
          'outline-color': theme('colors.primary.500'),
        },
        '.focus-ring:focus-visible': {
          outline: '2px solid ' + theme('colors.primary.500'),
        },
        '.dark .focus-ring:focus-visible': {
          'outline-color': theme('colors.primary.400'),
        },
      }
      
      addUtilities(newUtilities)
    }
  ],
} 